name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Run
        run: |
          sudo pip install -U wheel poetry
          poetry install
          poetry run python main.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: new-build
          commit-message: Update dashboards
          title: Update dashboards
          delete-branch: true
          signoff: true
